pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Unit Test') {
            steps {
                sh 'mvn -Dtest=BookServiceTests#testMethod test'
            }
            post {
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                }
            }
        }

        stage('Integration Test') {
            steps {
                sh 'mvn -Dtest=BookControllerIntegrationTests#testMethod test'
            }
            post {
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                }
            }
        }

        stage('Deploy to Container Directory') {
            steps {
                sh 'cp -r target/*.jar /jenkins_artifacts'
            }
        }
    }
}