pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Unit Test') {
            steps {
                sh 'mvn -Dtest=BookServiceTests#testMethod test'
            }
            post {
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                }
            }
        }

        stage('Integration Test') {
            steps {
                sh 'mvn -Dtest=BookControllerIntegrationTests#testMethod test'
            }
            post {
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                }
            }
        }

        stage('Deploy to Container Directory') {
            steps {
                // Assuming the build artifact is a jar file in the 'target' directory.
                // Adjust the file path according to your project structure.
                // Replace '/path/to/container/directory' with the actual path where you want to copy the artifact.
                sh 'cp target/*.jar'
            }
        }
    }
}